### ISSUE TITLE
macOS arm build app icon is blank

### ISSUE THREAD

**Issue by sslupsky** [FreeCAD/FreeCAD-Bundle#144]
A note to mention that the macOS arm build has a blank (all white) icon.
<img width="1032" alt="Screenshot 2022-12-13 at 12 33 51 PM" src="https://user-images.githubusercontent.com/16888734/207427968-008cdc87-91f4-407a-a0d3-6b43ca16962c.png">

**Comment by luzpaz** [comment]
@sslupsky please re-download macos conda and report back

**Comment by luzpaz** [comment]
This should be fixed. Closing.

**Comment by sslupsky** [comment]
Downloaded and looks good.  Thank you.

**Comment by sslupsky** [comment]
@luzpaz Actually, there is still a minor problem.  The icon in the dock still appears blank.

<img width="289" alt="Screenshot 2023-01-18 at 11 52 27 AM" src="https://user-images.githubusercontent.com/16888734/213269053-3db14d5b-58fc-49f4-9605-2a3f554a405a.png">

**Comment by luzpaz** [comment]
@sslupsky any idea why?

**Comment by sslupsky** [comment]
@luzpaz Not sure.  I removed the icon from the dock and it appeared blank when I opened FreeCAD.  I rebooted, hoping to clear some cache somewhere, but that did not fix the issue.  I'll have to dig around.  It may be an artifact of the earlier problem where something is cached someplace but I don't really know where to look for it at the moment.

**Comment by sslupsky** [comment]
@luzpaz Rebooting into Safe Mode seems to enough to clear the dock icon cache ... the icon is visible now.

**Comment by JohnOCFII** [comment]
FYI - the dock icon (as well as the icon in the Application folder) look fine for me with this version:
```[code]
OS: macOS 13.1
Word size of FreeCAD: 64-bit
Version: 0.21.0.31483 (Git)
Build type: Release
Branch: master
Hash: 588620fd9fd138892b1cd2466f5c87d441493174
Python 3.11.0, Qt 5.15.6, Coin 4.0.0, Vtk 9.2.2, OCC 7.6.3
Locale: C/Default (C)
[/code]
```
